CREATE TABLE SHIPWRECK (
  ID              INT AUTO_INCREMENT,
  NAME            NVARCHAR(255),
  DESCRIPTION     NVARCHAR(2000),
  CONDITION       NVARCHAR(255),
  DEPTH           DOUBLE,
  LATITUDE        DOUBLE,
  LONGITUDE       DOUBLE,
  YEAR_DISCOVERED INT
);
